-- Auto-generated from data/journal.json + data/products.json
-- Run AFTER 001_schema.sql in Supabase SQL Editor.
-- Idempotent-safe via TRUNCATE — re-running wipes and reloads.

truncate table product_items, product_series, journal restart identity cascade;

-- JOURNAL entries (newest first preserved via sort_order)
insert into journal (date, tag, emoji, title_ko, title_en, title_id, body_ko, body_en, body_id, sort_order) values ('May 8, 2026', 'meeting', '🤝', '부산 전략 회의', 'Strategy meeting in Busan', 'Rapat strategi di Busan', '저희 팀은 인도네시아 파트너의 2분기 시장 진출 계획을 조율하기 위해 부산에 모였습니다. 규제 일정, 주요 연락처 및 3개의 진행 중인 거래에 대한 다음 단계를 논의했습니다.', 'Our team gathered in Busan to align on Q2 market entry plans for Indonesian partners. We discussed regulatory timelines, key contacts, and next steps for three active deals.', 'Tim kami berkumpul di Busan untuk menyesuaikan rencana masuk pasar Q2 bagi mitra Indonesia. Kami mendiskusikan jadwal regulasi, kontak utama, dan langkah selanjutnya untuk tiga kesepakatan aktif.', 50);
insert into journal (date, tag, emoji, title_ko, title_en, title_id, body_ko, body_en, body_id, sort_order) values ('May 3, 2026', 'factory', '🏭', '공장 방문 — 술라웨시 니켈 가공 공장', 'Factory visit — Nickel processing plant, Sulawesi', 'Kunjungan pabrik — Pabrik pengolahan nikel, Sulawesi', '생산 능력과 품질 기준을 평가하기 위해 술라웨시에 있는 선도적인 니켈 가공 시설을 방문했습니다. 한국 배터리 제조업체와 잠재적인 공급 계약을 논의 중입니다.', 'We visited a leading nickel processing facility in Sulawesi to assess production capacity and quality standards. A potential supply agreement is under discussion with Korean battery manufacturers.', 'Kami mengunjungi fasilitas pengolahan nikel terkemuka di Sulawesi untuk menilai kapasitas produksi dan standar kualitas. Perjanjian pasokan potensial sedang dibahas dengan produsen baterai Korea.', 40);
insert into journal (date, tag, emoji, title_ko, title_en, title_id, body_ko, body_en, body_id, sort_order) values ('Apr 28, 2026', 'travel', '✈️', '자카르타 출장 — 파트너 온보딩', 'Business trip to Jakarta — partner onboarding', 'Perjalanan bisnis ke Jakarta — orientasi mitra', '크리스티안은 식음료 및 섬유 분야의 세 곳의 새로운 잠재 파트너를 만나기 위해 자카르타로 비행했습니다. 이틀 동안 생산적인 회의와 현장 방문이 진행되었습니다.', 'Christian flew to Jakarta to meet three new potential partners in the food & beverage and textile sectors. Productive meetings and site visits were held over two days.', 'Christian terbang ke Jakarta untuk bertemu tiga mitra potensial baru di sektor makanan & minuman dan tekstil. Pertemuan produktif dan kunjungan lapangan diadakan selama dua hari.', 30);
insert into journal (date, tag, emoji, title_ko, title_en, title_id, body_ko, body_en, body_id, sort_order) values ('Apr 20, 2026', 'field', '🌴', '현장 점검 — 칼리만탄 팜유 농장', 'Field check — Palm oil plantation, Kalimantan', 'Pemeriksaan lapangan — Perkebunan kelapa sawit, Kalimantan', '한국 식품 회사를 대신하여 칼리만탄의 팜유 농장을 현장 점검했습니다. 지속 가능성 인증, 물류 접근성 및 생산량을 확인했습니다.', 'We conducted a field inspection of a palm oil plantation in Kalimantan on behalf of a Korean food company. We checked sustainability certifications, logistics access, and output volumes.', 'Kami melakukan inspeksi lapangan perkebunan kelapa sawit di Kalimantan atas nama perusahaan makanan Korea. Kami memeriksa sertifikasi keberlanjutan, akses logistik, dan volume produksi.', 20);
insert into journal (date, tag, emoji, title_ko, title_en, title_id, body_ko, body_en, body_id, sort_order) values ('Apr 15, 2026', 'networking', '🤝', '한-인니 무역 포럼, 서울', 'Korea–Indonesia Trade Forum, Seoul', 'Forum Perdagangan Korea–Indonesia, Seoul', '상치컴퍼니는 서울에서 열린 한-인니 무역 포럼에 참가했습니다. 정부 무역 관계자, 물류 파트너, 그리고 양국 간의 기회를 모색하는 B2B 기업들과 네트워크를 형성했습니다.', 'Sangci Company participated in the Korea–Indonesia Trade Forum hosted in Seoul. We connected with government trade officials, logistics partners, and B2B companies exploring bilateral opportunities.', 'Sangci Company berpartisipasi dalam Forum Perdagangan Korea–Indonesia yang diadakan di Seoul. Kami terhubung dengan pejabat perdagangan pemerintah, mitra logistik, dan perusahaan B2B yang mengeksplorasi peluang bilateral.', 10);

-- PRODUCT SERIES + ITEMS (use CTEs to wire foreign keys)

with s as (
  insert into product_series (series_id, title_ko, title_en, title_id, desc_ko, desc_en, desc_id, sort_order) values (1, '아라비카 아체 가요 시리즈', 'Arabica Aceh Gayo Series', 'Seri Arabica Aceh Gayo', '인도네시아 아체 가요 고원지대의 비옥한 화산재 토양에서 자라 깊은 바디감과 복합적인 아로마를 자랑하는 시그니처 아라비카 라인업', 'Curated specialty Arabica coffees sourced directly from the volcanic highlands of Central Aceh, Indonesia.', 'Kopi Arabika specialty yang dikurasi langsung dari dataran tinggi vulkanik Aceh Tengah, Indonesia.', 10) returning id
)
insert into product_items (series_id, image, detail_img, name_ko, name_en, name_id, tags_ko, tags_en, tags_id, desc_ko, desc_en, desc_id, sort_order)
values
  ((select id from s), 'assets/gayo_plantation.png', 'assets/gayo_natural_detail.jpeg', '아라비카 아체 가요 내추럴', 'Arabica Aceh Gayo Natural', 'Arabica Aceh Gayo Natural', '["아체 센트럴","내추럴 프로세스","블랙베리","플로럴","스트롱 바디"]'::jsonb, '["Central Aceh","Natural Process","Blackberry","Floral","Strong Body"]'::jsonb, '["Aceh Tengah","Proses Natural","Blackberry","Floral","Body Tebal"]'::jsonb, '복합적인 베리 향미와 묵직한 바디감을 가진 아체 센트럴 지역의 프리미엄 아라비카.', 'Premium Arabica from Central Aceh with a complex berry profile and heavy body.', 'Arabika premium dari Aceh Tengah dengan rasa beri kompleks dan body tebal.', 10),
  ((select id from s), 'assets/roasted_beans.png', '', '아라비카 아체 가요 풀워시드', 'Arabica Aceh Gayo Full-washed', 'Arabica Aceh Gayo Full-washed', '["아체 센트럴","풀워시드 프로세스","플로럴","프루티","초콜릿","스트롱 바디"]'::jsonb, '["Central Aceh","Full-washed Process","Floral","Fruity","Chocolate","Strong Body"]'::jsonb, '["Aceh Tengah","Proses Full-washed","Floral","Fruity","Cokelat","Body Tebal"]'::jsonb, '화사한 꽃향기와 달콤한 초콜릿 피니시가 균형 잡힌 깔끔한 커피.', 'Clean, bright floral notes balanced with sweet chocolate undertones.', 'Rasa floral yang bersih dan cerah dipadukan dengan sentuhan cokelat manis.', 20),
  ((select id from s), 'assets/specialty_pour_over.png', '', '아라비카 아체 가요 세미워시드', 'Arabica Aceh Gayo Semi-washed', 'Arabica Aceh Gayo Semi-washed', '["아체 센트럴","세미워시드 프로세스","허브","스파이시","클린 피니시"]'::jsonb, '["Central Aceh","Semi-washed Process","Herbal","Spicy","Clean Finish"]'::jsonb, '["Aceh Tengah","Proses Semi-washed","Herbal","Rempah","Akhir yang Bersih"]'::jsonb, '풍부한 허브 스파이스와 깔끔한 끝맛을 자랑하는 전통 인도네시아 세미워시드 커피.', 'Traditional Indonesian wet-hulled cup offering rich herbal spices and a clean finish.', 'Kopi giling basah tradisional dengan rempah herbal melimpah dan akhir bersih.', 30);

with s as (
  insert into product_series (series_id, title_ko, title_en, title_id, desc_ko, desc_en, desc_id, sort_order) values (2, '아라비카 만데링 시리즈', 'Arabica Mandheling Series', 'Seri Arabica Mandheling', '이색적인 천연 가향 공법을 결합하여 독보적인 아로마와 부드러운 바디감을 구현한 전 세계가 사랑하는 만데링 시리즈', 'World-renowned Sumatran coffees featuring exotic infused aromatics and rich, deep cup characteristics.', 'Kopi Sumatra yang terkenal di dunia menampilkan aromatik infus eksotis dan karakteristik rasa yang kaya dan mendalam.', 20) returning id
)
insert into product_items (series_id, image, detail_img, name_ko, name_en, name_id, tags_ko, tags_en, tags_id, desc_ko, desc_en, desc_id, sort_order)
values
  ((select id from s), 'assets/specialty_pour_over.png', '', '아라비카 만데링 자스민', 'Arabica Mandheling Jasmine', 'Arabica Mandheling Jasmine', '["북수마트라","인퓨즈드 프로세스","자스민 티","플로럴"]'::jsonb, '["North Sumatra","Infused Process","Jasmine Tea","Floral"]'::jsonb, '["Sumatra Utara","Proses Infused","Teh Melati","Floral"]'::jsonb, '천연 자스민을 가향하여 은은하고 향긋한 자스민 차의 느낌을 더한 프리미엄 만데링.', 'Premium Mandheling Arabica infused with natural jasmine for an aromatic tea-like finish.', 'Arabika Mandheling pilihan yang diinfusi melati alami untuk rasa seperti teh aromatik.', 10),
  ((select id from s), 'assets/roasted_beans.png', '', '아라비카 만데링 피치', 'Arabica Mandheling Peach', 'Arabica Mandheling Peach', '["북수마트라","인퓨즈드 프로세스","복숭아","단맛"]'::jsonb, '["North Sumatra","Infused Process","Peach","Sweetness"]'::jsonb, '["Sumatra Utara","Proses Infused","Persik","Manis"]'::jsonb, '주시하고 달콤한 복숭아 향이 만데링의 부드러운 바디감과 어우러진 조화로운 맛.', 'Juicy and sweet peach infusion combined with the smooth body of Mandheling.', 'Infusi persik manis juicy dipadukan dengan body lembut khas Mandheling.', 20),
  ((select id from s), 'assets/harvest_hands.png', '', '아라비카 만데링 코코넛', 'Arabica Mandheling Coconut', 'Arabica Mandheling Coconut', '["북수마트라","인퓨즈드 프로세스","코코넛","크리미"]'::jsonb, '["North Sumatra","Infused Process","Coconut","Creamy"]'::jsonb, '["Sumatra Utara","Proses Infused","Kelapa","Creamy"]'::jsonb, '크리미한 코코넛의 고소함과 이색적인 열대 정취를 느낄 수 있는 독특한 커피.', 'Unique tropical profile showcasing a creamy coconut aroma and balanced finish.', 'Profil tropis unik dengan aroma kelapa yang creamy dan akhir seimbang.', 30),
  ((select id from s), 'assets/gayo_plantation.png', '', '아라비카 만데링 스트로베리', 'Arabica Mandheling Strawberry', 'Arabica Mandheling Strawberry', '["북수마트라","인퓨즈드 프로세스","딸기","프루티"]'::jsonb, '["North Sumatra","Infused Process","Strawberry","Fruity"]'::jsonb, '["Sumatra Utara","Proses Infused","Stroberi","Fruity"]'::jsonb, '달콤한 딸기 향이 만데링 특유의 다크 초콜릿 마우스필과 환상적인 조화를 이룹니다.', 'Sweet strawberry notes that complement Mandheling''s dark chocolate base.', 'Aroma stroberi manis yang melengkapi dasar cokelat hitam khas Mandheling.', 40);

with s as (
  insert into product_series (series_id, title_ko, title_en, title_id, desc_ko, desc_en, desc_id, sort_order) values (3, '아라비카 & 로부스타 시리즈', 'Arabica & Robusta Series', 'Seri Arabica & Robusta', '수마트라 케린치 지역의 화사한 싱글 오리진 아라비카와 자바 섬 테망궁 지역의 잡미 없이 깨끗하고 묵직한 프리미엄 로부스타 라인업', 'Vibrant single-origin Arabica from Kerinci region and clean, high-grade bold Robusta from Temanggung, Java.', 'Arabika single-origin yang cerah dari wilayah Kerinci dan Robusta bold bermutu tinggi dari Temanggung, Jawa.', 30) returning id
)
insert into product_items (series_id, image, detail_img, name_ko, name_en, name_id, tags_ko, tags_en, tags_id, desc_ko, desc_en, desc_id, sort_order)
values
  ((select id from s), 'assets/harvest_hands.png', '', '아라비카 케린치 내추럴', 'Arabica Kerinci Natural', 'Arabica Kerinci Natural', '["수마트라 케린치","내추럴 프로세스","시트러스","딸기","복숭아","망고"]'::jsonb, '["Kerinci, Sumatra","Natural Process","Citrus","Strawberry","Peach","Mango"]'::jsonb, '["Kerinci, Sumatra","Proses Natural","Sitrus","Stroberi","Persik","Mangga"]'::jsonb, '열대 과일(복숭아, 망고)과 시트러스의 상큼하고 달콤한 풍미가 돋보이는 내추럴 커피.', 'Vibrant, sweet natural coffee bursting with tropical peach and mango flavors.', 'Kopi natural yang manis dan cerah dengan rasa persik tropis dan mangga.', 10),
  ((select id from s), 'assets/roasted_beans.png', '', '로부스타 테망궁 워시드', 'Robusta Temanggung Washed', 'Robusta Temanggung Washed', '["중부 자바 테망궁","워시드 프로세스","너티","볼드","다크 초콜릿"]'::jsonb, '["Temanggung, Central Java","Washed Process","Nutty","Bold","Dark Chocolate"]'::jsonb, '["Temanggung, Jawa Tengah","Proses Washed","Nutty","Bold","Cokelat Hitam"]'::jsonb, '잡미 없이 깔끔한 고품질 로부스타로, 묵직한 마우스필과 쌉싸름하면서도 달콤한 다크 초콜릿 풍미.', 'High-quality robusta offering a bold, clean body with a rich chocolate sweetness.', 'Robusta bermutu tinggi dengan body tebal, rasa nutty, dan kemanisan cokelat pekat.', 20);
